### ISSUE TITLE
GoView can't display ElementarySurface: Disc

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF-Geometry/GoTools#186]
Geometry file with an axis cross (3 `Line`), followed by a `Cylinder`, `Sphere` and a `Disc`. Only 5 of the 6 objects is displayed in goview.

![nodisc](https://user-images.githubusercontent.com/3500376/35963317-a68af56a-0cb4-11e8-8e12-9abbc13968e4.png)

# G2 file
```
120 1 0 0

3
-1 0 0
1 0 0
1
0 6
0

120 1 0 0

3
0 -1 0
0 1 0
1
0 6
0

120 1 0 0

3
0 0 -1
0 0 1
1
0 6
0

260 1 0 0

3
2
1 0 0
-0.707106781186547 0 0.707106781186547
0.707106781186548 0 0.707106781186547
0
0 6.28318530717959
0

270 1 0 0

3
1.5
4 0 0
0 0.707106781186547 0.707106781186547
1 0 0
0 6.28318530717959
-1.5707963267949 1.5707963267949
0

292 1 0 0

3
6 0 0
2.5
1 0 0
0 0 -1
1
0
1.5707963267949
3.14159265358979
4.71238898038469
0 2.5
0 6.28318530717959
0
```

**Comment by VikingScientist** [comment]
Also: if you add an Elementary surface: `Torus` to the end of the input file, then goview fails to show *any* of the geometries.

![no-geometries](https://user-images.githubusercontent.com/3500376/35963638-ada954e4-0cb5-11e8-8261-c9bf1c592360.png)

# G2 file
```
120 1 0 0

3
-1 0 0
1 0 0
1
0 6
0

120 1 0 0

3
0 -1 0
0 1 0
1
0 6
0

120 1 0 0

3
0 0 -1
0 0 1
1
0 6
0

260 1 0 0

3
2
1 0 0
-0.707106781186547 0 0.707106781186547
0.707106781186548 0 0.707106781186547
0
0 6.28318530717959
0

270 1 0 0

3
1.5
4 0 0
0 0.707106781186547 0.707106781186547
1 0 0
0 6.28318530717959
-1.5707963267949 1.5707963267949
0

292 1 0 0

3
6 0 0
2.5
1 0 0
0 0 -1
1
0
1.5707963267949
3.14159265358979
4.71238898038469
0 2.5
0 6.28318530717959
0

290 1 0 0

3
14
2
9 0 0
0 0 1
0.707106781186547 0.707106781186547 0
1
0 6.28318530717959
0 6.28318530717959
0
```

**Comment by sbriseid** [comment]
Due to roundoff error the domain was illegal. I've added a numerical tolerance to the Disc read method. Additionally I've enabled support for Disc in goview.

The g2 format is really bad at handling errors. The correct way to handle file reading is to parse the file before doing anything that may cause an exception to be thrown. This is unfortunately not the way it is done, resulting in the last 0 of the Disc object being interpreted as an illegal ClassType. With our new g22 file format such errors will not be a problem as all objects are placed inside xml tags. We will soon update goview to support g22 files.
