### ISSUE TITLE
LoopUtils::representAsSurfaceCurves returns unexpected results

### ISSUE THREAD

**Issue by ikoruk** [SINTEF-Geometry/GoTools#204]
From the signature,
```
    void representAsSurfaceCurves(std::vector< shared_ptr<ParamCurve> >& curves,
				  shared_ptr<BoundedSurface> surf,
				  std::vector<shared_ptr<CurveOnSurface> >& cvs_on_sf);
```

One would expect that it takes curves and returns into the cvs_on_sf, however, if they are not already surface curves, it instead overwrites sfcv which is a local variable and then returns all nulls.

I suspect that the `else` on line 114 of LoopUtils.C should not be there.

**Comment by ikoruk** [comment]
Anyone?

**Comment by sbriseid** [comment]
Hi there! Your issue slipped under the radar of our semi-existent support team, and your reminder occurred during the rather long summer holidays here in Norway ...

I totally agree the else on line 114 is of no use. I don't see that it would cause any real harm (assigning a shared_ptr), but it should nonetheless be removed (I'll address it in a pull request). Did this function trigger any bugs? If so they do not appear to be related to the else-statement.

**Comment by sbriseid** [comment]
Looking at the creation of the CurveOnSurface, the BoundedSurface is used instead of the underlying surface, which is hardly the intention. This function is not called very often, mainly used by some utility functions in compositemodel. I'll look into the issue.

**Comment by ikoruk** [comment]
The issue is more that with the else there on line 114, the `if (cvdim == sfdim && sfdim > 2)` and `else if (cvdim == 2)` blocks do computation and then don't actually return their result.

**Comment by sbriseid** [comment]
Ok, reading a bit fast I thought that the else on line 114 was a summary of your issues. This short function really is a mess ... I totally agree that the result should be put into the cvs_on_sf vector. I am suspecting that our limited usage of this function has solely dealt with the CurveOnSurface type (in which case the casted curves are returned), otherwise there is no reason to expect anything sensible ...

Thanks for the bug report! I'll create a fix right away and run some tests.

**Comment by sbriseid** [comment]
Resolved.
